name: Chrome headless
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          #headless: true
          start: npx ng serve
          # wait for server to start
          wait-on: 'http://localhost:4200'
          # wait for 2 minutes for the server to respond
          wait-on-timeout: 120
